### PR TITLE
[1.19.4] Extend German translation and backport localization updates

### PR DESCRIPTION
**Pull request by Doenerstyle**

### CODE REVIEW

**Comment by qznfbnj** [comment]
Ooch, you seems to revert my zh_cn.json update... I will update completely when I have time in the future.
image
image

**Comment by Doenerstyle** [comment]
@qznfbnj Hello, as explained in #188, I based the translations for the sync on the 1.20.1 branch. Since your changes were only on 1.19.x, they were overwritten - sorry about that. 😅

If you don't mind, I'm sure people would appreciate it if you update your localization on all (or at least the most popular) versions! :)

**Comment by jaredlll08** [comment]
@qznfbnj I am sorry about that, I should have seen that when I merged the PRs.

If you wouldn't mind, please can you remake the PRs, or if you would prefer, I can commit the changes myself when I get time.

**Comment by qznfbnj** [comment]
> If you wouldn't mind, please can you remake the PRs, or if you would prefer, I can commit the changes myself when I get time.

Oh, it would be great if you could submit changes to the versions you still support.
 Of course, if I'm free in the future and you haven't submitted the changes yet, I'll make a(or some) new PR.

**Pull request merged**
