### PR TITLE
Improvement GUI

### PR DESCRIPTION
**Pull request by TheDirectorX**
**Here's what it looks like:**

Wide buttons solve the problem of non-fit text in other languages ​​and because of this it looks much better.
### What was conceived but not implemented due to lack of knowledge in Minecraft modding [Need help]:
1. **Make "Search by" be centered along with CheckBox and the word after it.** So that `the characters "Search by" (+ indentation of 5 pixels) + the length of the CheckBox + the length of characters after the CheckBox are taken into account` and all this is aligned in the center of the search field. _To align this box in different languages._
image
2. **Add/Return Available Keys Interface (Toggle Free).** In the button `?`
I think that the **Patreon** button will look too intrusive in the standard Minecraft menu. _You can also leave a link to Patreon in the Mods tab._ But if you still want to leave it, it is better to do it in place of the `?` button. Using the [official corporate logo](https://www.patreon.com/brand).
3. **Remove excess animated texture when hovering over CheckBox buttons.** As for me, a white outline is enough. _The first time I thought it was a texture bug._
image
### Known bugs:
* **Highlighting another button behind Background when hovering.**
image
**Related.** At the shadow of the text:
Screen
* **Interface elements on top of category popup text.**
image
image

**And finally, don't forget to update the version of the mod in mods.toml ;)** https://github.com/jaredlll08/Controlling/blob/75c83d7a6789bc88b6a33bff313fffc30d59808f/src/main/resources/META-INF/mods.toml#L8

### CODE REVIEW

**Comment by jaredlll08** [comment]
Thank you, but no thanks.

So firstly, I never liked the free keys, it was badly implemented, didn't look good and I had no way to make it look good.

Secondly, I kinda like how the GUI looks, and no one has complained about it yet.

In general I just feel like this is a step backwards, and will confuse people (especially now that they need to click an extra button to show conflicting keys, they may think it was removed).

**Comment by TheDirectorX** [comment]
**Okay, what about some inability to localize some text?**
https://github.com/jaredlll08/Controlling/blob/75c83d7a6789bc88b6a33bff313fffc30d59808f/src/main/java/com/blamejared/controlling/client/gui/GuiNewControls.java#L97
https://github.com/jaredlll08/Controlling/blob/75c83d7a6789bc88b6a33bff313fffc30d59808f/src/main/java/com/blamejared/controlling/client/gui/SortOrder.java#L31-L35
**Just like in English, the text is right next to the edges of the button:**
image
**So in almost all other languages it will be like this:**
image

**What about these two commits?**
e1bac629b075f9bddfe1adb570683fd1094a0743 023e25fe7fe9eb6257d1530c66e2f4535a212c0c

**I wrote that if you still don't want to add Toggle Free, you can replace the square button that I added with the Patreon button (with their logo). I think the Patreon button will look better.**
> I think that the **Patreon** button will look too intrusive in the standard Minecraft menu. _You can also leave a link to Patreon in the Mods tab._ But if you still want to leave it, it is better to do it in place of the `?` button. Using the [official corporate logo](https://www.patreon.com/brand).

**And finally, the bugs that I described, which you may know about. Is it possible to solve them?**

**Comment by jaredlll08** [comment]
Button localization is just an inherent issue with any button, not mine specifically, you could reproduce similar things with localization and any vanilla button, there isn't really a good fix unfortunately.

https://github.com/jaredlll08/Controlling/commit/e1bac629b075f9bddfe1adb570683fd1094a0743 is actually kinda interesting, and I may implement that.

https://github.com/jaredlll08/Controlling/commit/023e25fe7fe9eb6257d1530c66e2f4535a212c0c
Changing that is going to lead to localization issues as it is already translated in other languages, so doing it will be confusing.

Using the Patreon logo for the button would be pretty interesting, but if I made the button smaller, it would look out of place. If I ever change the gui I will look into it.

Now the bugs.

The text shadow I have a fix for, fix being just remove the shadow (no other text on the screen has it, it was a mistake to begin with).

The selecting box underneath the menu is a vanilla bug (or at least forge, basically I can reproduce without my mod):
image

The elements overlapping the text is a bit of an issue though, I'm not sure how I would go about fixing that.

Hard coding "Show All" is a bug, I already have a translation for it, so I should be using that instead.

I'll add translations for the rest though

**Comment by jaredlll08** [comment]
also ```
Remove excess animated texture when hovering over CheckBox buttons. As for me, a white outline is enough. The first time I thought it was a texture bug.
```
is a texture bug kinda, I'm removing it

**Comment by TheDirectorX** [comment]
> 023e25f
> Changing that is going to lead to localization issues as it is already translated in other languages, so doing it will be confusing.

This is easy to solve, I have already added translations to almost all languages (locally). The values for comparison can be taken from the official website of the translation: [Minecraft translations in Crowdin](https://crowdin.com/translate/minecraft). The problem can only occur in **Chinese** and **Pirated English** (I'm not at all sure of them). Even for **Japanese** added. `¯\_(ツ)_/¯`


You can still view my **commits**, maybe something will interest you. I specifically made it so that you can easily make **revert** without consequences.

**Comment by Greg-21** [comment]
I really like this GUI redesign, and the thing I like the most is the merger of "Show Conflicts", "Show Unbound", and "Show All" buttons. As for me one button that you click to cycle through all the different display modes is much more intuitive and familiar, as vanilla Minecraft already has had such buttons for years. Wide button also solves the localization issues you mentioned before. Earlier today I created a pull request (#61), in which, among others, I shortened button labels ("Show All", "Show Conflicts", and "Show Unbound" to "All", "Conflicts", and "Unbound" respectively), and I know that they lost some of their readability, but because they were exceeding button width and were overlapping each other, in some sense I was forced to do so.

The small "?" label can be replaced by i.e. a pixelated Patreon logo and will match the vanilla language, accessibility and difficulty lock buttons. Additionally, a colorful icon will be more eye-catching than just a plain text.

**Pull request closed without merging**
