### PR TITLE
Remove unused patron code, restore overriden zh_CN localization update

### PR DESCRIPTION
**Pull request by Doenerstyle**
To me it seems like that code was indeed unused, so I'm bringing it here for more people to benefit from this. I assume this could be ported to more recent versions too.
While I was working on 1.7.10 anyways, I also restored the lost localization update from #144.

**Out of all my localization updates, only 1.20.x, 1.16.5, and 1.12.2 versions have been released so far.
I understand that it might be a lot of work to release from all branches, I'd be thankful if you could release a new 1.7.10 build soon. :)**
`gradlew build` works fine for the 1.7.10 branch.

### CODE REVIEW

**Comment by jaredlll08** [comment]
Thanks!

The version should get built my by CI, hopefully it doesn't fail for 1.7.10

**Comment by Doenerstyle** [comment]
https://ci.blamejared.com/job/Jared/job/Minecraft%20Mods/job/Controlling/job/1.7.10/7/console
@jaredlll08 seems like the CI failed. :/
I'm not sure why the daemon "doesn't work" there, but we could possibly un-disable the daemon in `gradle.properties,` which might or might not fix that. 🤷🏻‍♂️
Other than that, you probably know way better about Jenkins and your CI than I do. :)

**Comment by jaredlll08** [comment]
Seems like the last few builds have been failing due to me updating java on the box, and I never updated the jenkinsfile for 1.7.10, should be fixed now

**Comment by Doenerstyle** [comment]
I see, maybe that's the issue for the other Java 8 versions too then. 🤔
Thanks a lot! ❤️

**Pull request merged**
