### PR TITLE
Update ru_RU.lang

### PR DESCRIPTION
**Pull request by Bytegm**

### CODE REVIEW

**Comment by jaredlll08** [comment]
May I ask why you closed this?

**Comment by Bytegm** [comment]
> May I ask why you closed this?

I have a similar question for you - why didn’t you merge this?

**Comment by jaredlll08** [comment]
I've been extremely busy in life, in my last semester of my last year of university, I haven't exactly had time to release mods. Even if I had merged this PR, it wouldn't have been released anytime soon, I personally find it easier to keep PRs open, and then merge them when I actually have time to do releases, that way I know what has changed instead of having to look through commit history.

**Comment by jaredlll08** [comment]
Manually added in:
https://github.com/jaredlll08/Controlling/commit/1feaa98561c12ffdf4ab517637439fac091c713c

Finally got time to release, like I said.

**Pull request closed without merging**
